
task: classify
method: pi
ambient_dims: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

hom_dims: [0, 1]

dataset_path_template: data/{ambient_dim}d/images.pkl
output_dir_template: results/classify/{ambient_dim}d/pi/h{hom_dim}

batch_size: 32
n_epochs: 500
lr: 0.001
embedding_dim: 128
seed: 0